"""Add the 21-year through-cycle test (table + factsheet) to the gtaa-etf-rotation study
and correct the period-dependence caveat with real through-cycle numbers."""
from pathlib import Path
P = Path("/home/arun/quantifyd/frontend/src/data/backtests.ts")
ts = P.read_text()
if "Through-cycle stress test" in ts:
    print("already added"); raise SystemExit

# A) second chart (21y factsheet) after the gtaa factsheet chart
chart_anchor = """            'CLIENT FACTSHEET — GTAA Equal-Weight 3-Asset (Nifty + Gold + Nasdaq-100) vs NIFTY 50, 2016–2026, net of 20 bps. KPI strip, growth-of-₹1 (log), drawdown-vs-index, annual bars, monthly heatmap, rolling 12m, stat tables. 19.7% CAGR vs 14% (this view), 6.4x, Sharpe 1.04 (rf-adj), Calmar 1.75, MaxDD −11.3%, 55% of years beating the index. Generated by research/_utilities/tearsheet.py.',
        },"""
chart_new = chart_anchor + """
        {
          src: '/app/gtaa-longhist-factsheet.png',
          caption:
            'THROUGH-CYCLE (21y, 2005–2026, incl. 2008 GFC) — 3-asset equal-weight vs NIFTY 50. Gold/Nasdaq pre-2015 are proxies (GLD/QQQ × USDINR, validated corr 0.88/0.71); real ETFs post-2015. The honest full-cycle picture: CAGR 17.2% vs 12.7%, MaxDD −23.8% vs −55.2%, Calmar 0.72 (0.82 inverse-vol) vs 0.23. The recent decade\\'s −11% DD / 1.7 Calmar was a benign-period artifact; through a real crisis even uncorrelated assets fall together (2008: −21% vs Nifty −52%).',
        },"""
assert chart_anchor in ts, "chart anchor missing"
ts = ts.replace(chart_anchor, chart_new, 1)

# B) through-cycle comparison table after the silver addendum table
silver_anchor = """          ['4-asset (+Silver), inverse-vol', '2022–26', '24.5%', '−9.4%', '2.61'],
        ],
        highlightRows: [0],
        heatmap: false,
      },"""
tc_table = silver_anchor + """
      {
        title: 'Through-cycle stress test — extended to 21y (2005–2026) via gold/Nasdaq proxies',
        caption: 'Factor data is post-2015 only, so this uses Nifty as the equity sleeve. Gold = GLD × USDINR, Nasdaq = QQQ × USDINR (validated vs the real ETFs, corr 0.88 / 0.71), chained with real ETFs post-2015. Finally includes 2008/2011/2013 — and shows the recent −11% DD was a benign-period artifact.',
        columns: ['Book / period', 'CAGR', 'MaxDD', 'Calmar'],
        rows: [
          ['3-asset equal — 21y (2005–26)', '17.2%', '−23.8%', '0.72'],
          ['3-asset inverse-vol — 21y', '17.1%', '−20.9%', '0.82'],
          ['Nifty only — 21y', '12.7%', '−55.2%', '0.23'],
          ['2008 GFC year: 3-asset vs Nifty', '−21% / −52%', '—', '—'],
          ['2011: 3-asset vs Nifty (gold carried)', '+8% / −24%', '—', '—'],
          ['recent 2015–26 sub-period (for contrast)', '17.6%', '−11.3%', '1.57'],
        ],
        highlightRows: [0, 1],
        heatmap: false,
      },"""
assert silver_anchor in ts, "silver anchor missing"
ts = ts.replace(silver_anchor, tc_table, 1)

# C) correct the period-dependence caveat
cav_anchor = "'Period dependence (biggest): 2016–2026 was a golden decade for this trio — MON100’s +24.6% INR CAGR (Nasdaq mega-bull + ~3%/yr INR depreciation) carries much of the absolute return and will NOT repeat at that rate. The low-DD / diversification / Calmar property is the robust takeaway; treat ~19% CAGR as an upper bound, not a forecast (forward-realistic ≈ 10–13% CAGR, −15 to −20% DD in a less benign regime).',"
cav_new = "'Period dependence (RESOLVED 2026-06-14): the headline 1.7 Calmar / −11% DD is a 2016–26 benign-period artifact. Extending to 21y (2005–26) via validated gold/Nasdaq proxies (Nifty as the equity sleeve, since factor/ETF data is post-2015) gives the THROUGH-CYCLE truth: Calmar ~0.72 (0.82 inverse-vol), MaxDD −23.8%, CAGR 17.2%. In a real crisis (2008) even uncorrelated assets fall together → −24%, not −11%. The durable claim stands: vs Nifty-only the book HALVES drawdown (−24% vs −55%) and adds ~4.5%/yr (17.2% vs 12.7%), Calmar 0.8 vs 0.23 — a real all-weather core, just expect ~−24% DD through a crisis, not −11%.',"
assert cav_anchor in ts, "caveat anchor missing"
ts = ts.replace(cav_anchor, cav_new, 1)

P.write_text(ts)
print("research/63 updated: through-cycle table + 21y factsheet + corrected caveat")
