"""
Universal Intraday Backtest Engine
===================================
Strategy-agnostic backtesting for intraday/short-term trading systems.

Features:
- Long and Short trades
- Multiple exit types: Fixed SL/TP, Trailing SL (ATR/SuperTrend), EOD
- Per-trade and per-year performance tracking
- Works with any timeframe (5-min, 60-min, daily)
- Futures and Cash mode (with lot sizes for futures)

Usage:
    from services.intraday_backtest_engine import IntradayBacktestEngine, TradeSignal

    engine = IntradayBacktestEngine(
        data=df,  # OHLCV DataFrame
        initial_capital=1_000_000,
        mode='cash',  # or 'futures'
    )

    # Feed signals bar by bar
    for i in range(len(df)):
        signal = my_strategy(df, i)  # Returns TradeSignal or None
        engine.process_bar(i, signal)

    result = engine.get_results()
"""

import numpy as np
import pandas as pd
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Tuple
from enum import Enum


class Direction(Enum):
    LONG = 1
    SHORT = -1


class ExitType(Enum):
    FIXED_SL = 'fixed_sl'
    FIXED_TP = 'fixed_tp'
    TRAILING_SL = 'trailing_sl'
    SUPERTREND_FLIP = 'supertrend_flip'
    EOD = 'eod'
    SIGNAL_EXIT = 'signal_exit'
    MAX_HOLD = 'max_hold'


@dataclass
class TradeSignal:
    """Signal generated by a strategy."""
    direction: Direction
    entry_price: float
    stop_loss: float
    target: Optional[float] = None
    trailing_atr_mult: Optional[float] = None  # For ATR trailing SL
    max_hold_bars: Optional[int] = None  # Max bars to hold


@dataclass
class Trade:
    """Completed trade record."""
    symbol: str
    direction: Direction
    entry_date: str
    entry_price: float
    exit_date: str
    exit_price: float
    stop_loss: float
    target: Optional[float]
    pnl: float
    pnl_pct: float
    exit_type: ExitType
    bars_held: int
    year: int


@dataclass
class Position:
    """Active position."""
    symbol: str
    direction: Direction
    entry_price: float
    entry_bar: int
    entry_date: str
    stop_loss: float
    target: Optional[float]
    trailing_atr_mult: Optional[float]
    max_hold_bars: Optional[int]
    highest_since_entry: float = 0.0
    lowest_since_entry: float = float('inf')
    quantity: int = 1


@dataclass
class BacktestResult:
    """Complete backtest results."""
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_pnl: float = 0.0
    total_pnl_pct: float = 0.0
    profit_factor: float = 0.0
    max_drawdown: float = 0.0
    max_drawdown_pct: float = 0.0
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0
    calmar_ratio: float = 0.0
    cagr: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    avg_rr: float = 0.0  # Average risk:reward achieved
    avg_bars_held: float = 0.0
    long_trades: int = 0
    short_trades: int = 0
    long_win_rate: float = 0.0
    short_win_rate: float = 0.0
    trades: List[Trade] = field(default_factory=list)
    equity_curve: Dict[str, float] = field(default_factory=dict)
    yearly_stats: Dict[int, Dict] = field(default_factory=dict)
    exit_reasons: Dict[str, int] = field(default_factory=dict)
    monthly_returns: Dict[str, float] = field(default_factory=dict)


class IntradayBacktestEngine:
    """
    Universal backtest engine for intraday strategies.

    Supports:
    - Single symbol or multi-symbol
    - Long and short
    - Multiple exit types
    - Per-bar processing with external signal generation
    """

    def __init__(
        self,
        initial_capital: float = 1_000_000,
        position_size_pct: float = 0.10,  # 10% of capital per trade
        max_positions: int = 5,
        commission_pct: float = 0.0005,  # 0.05% round trip (futures ~0.01%)
        slippage_pct: float = 0.0005,   # 0.05% slippage
        mode: str = 'cash',  # 'cash' or 'futures'
        fixed_sizing: bool = True,  # Use initial capital for sizing (no compounding)
    ):
        self.initial_capital = initial_capital
        self.capital = initial_capital
        self.position_size_pct = position_size_pct
        self.max_positions = max_positions
        self.commission_pct = commission_pct
        self.slippage_pct = slippage_pct
        self.mode = mode
        self.fixed_sizing = fixed_sizing

        self.positions: Dict[str, Position] = {}
        self.trades: List[Trade] = []
        self.equity_curve: Dict[str, float] = {}
        self.peak_equity = initial_capital
        self.max_drawdown = 0.0
        self.exit_reasons: Dict[str, int] = {}

    def _get_position_size(self, price: float) -> int:
        """Calculate number of shares/lots for a trade."""
        base = self.initial_capital if self.fixed_sizing else self.capital
        alloc = base * self.position_size_pct
        qty = int(alloc / price)
        return max(qty, 1)

    def _apply_slippage(self, price: float, direction: Direction, is_entry: bool) -> float:
        """Apply slippage to price."""
        if is_entry:
            if direction == Direction.LONG:
                return price * (1 + self.slippage_pct)
            else:
                return price * (1 - self.slippage_pct)
        else:
            if direction == Direction.LONG:
                return price * (1 - self.slippage_pct)
            else:
                return price * (1 + self.slippage_pct)

    def open_position(
        self,
        symbol: str,
        signal: TradeSignal,
        bar_idx: int,
        bar_date: str,
    ) -> bool:
        """Open a new position. Returns True if opened."""
        if symbol in self.positions:
            return False
        if len(self.positions) >= self.max_positions:
            return False

        entry_price = self._apply_slippage(signal.entry_price, signal.direction, True)
        qty = self._get_position_size(entry_price)

        self.positions[symbol] = Position(
            symbol=symbol,
            direction=signal.direction,
            entry_price=entry_price,
            entry_bar=bar_idx,
            entry_date=bar_date,
            stop_loss=signal.stop_loss,
            target=signal.target,
            trailing_atr_mult=signal.trailing_atr_mult,
            max_hold_bars=signal.max_hold_bars,
            highest_since_entry=entry_price,
            lowest_since_entry=entry_price,
            quantity=qty,
        )
        return True

    def close_position(
        self,
        symbol: str,
        exit_price: float,
        bar_idx: int,
        bar_date: str,
        exit_type: ExitType,
    ) -> Optional[Trade]:
        """Close a position and record the trade."""
        if symbol not in self.positions:
            return None

        pos = self.positions[symbol]
        exit_price = self._apply_slippage(exit_price, pos.direction, False)

        if pos.direction == Direction.LONG:
            pnl_per_share = exit_price - pos.entry_price
        else:
            pnl_per_share = pos.entry_price - exit_price

        gross_pnl = pnl_per_share * pos.quantity
        commission = (pos.entry_price + exit_price) * pos.quantity * self.commission_pct
        net_pnl = gross_pnl - commission
        pnl_pct = (pnl_per_share / pos.entry_price) * 100

        self.capital += net_pnl

        year = int(bar_date[:4]) if isinstance(bar_date, str) else bar_date.year

        trade = Trade(
            symbol=symbol,
            direction=pos.direction,
            entry_date=pos.entry_date,
            entry_price=pos.entry_price,
            exit_date=bar_date,
            exit_price=exit_price,
            stop_loss=pos.stop_loss,
            target=pos.target,
            pnl=net_pnl,
            pnl_pct=pnl_pct,
            exit_type=exit_type,
            bars_held=bar_idx - pos.entry_bar,
            year=year,
        )

        self.trades.append(trade)
        self.exit_reasons[exit_type.value] = self.exit_reasons.get(exit_type.value, 0) + 1
        del self.positions[symbol]
        return trade

    def check_exits(
        self,
        symbol: str,
        bar_idx: int,
        bar_date: str,
        high: float,
        low: float,
        close: float,
        atr: Optional[float] = None,
        supertrend_dir: Optional[int] = None,
        is_eod: bool = False,
    ) -> Optional[Trade]:
        """Check all exit conditions for an open position."""
        if symbol not in self.positions:
            return None

        pos = self.positions[symbol]

        # Update trailing levels
        if high > pos.highest_since_entry:
            pos.highest_since_entry = high
        if low < pos.lowest_since_entry:
            pos.lowest_since_entry = low

        # --- Check Stop Loss (hit within bar) ---
        if pos.direction == Direction.LONG and low <= pos.stop_loss:
            return self.close_position(symbol, pos.stop_loss, bar_idx, bar_date, ExitType.FIXED_SL)
        if pos.direction == Direction.SHORT and high >= pos.stop_loss:
            return self.close_position(symbol, pos.stop_loss, bar_idx, bar_date, ExitType.FIXED_SL)

        # --- Check Target ---
        if pos.target is not None:
            if pos.direction == Direction.LONG and high >= pos.target:
                return self.close_position(symbol, pos.target, bar_idx, bar_date, ExitType.FIXED_TP)
            if pos.direction == Direction.SHORT and low <= pos.target:
                return self.close_position(symbol, pos.target, bar_idx, bar_date, ExitType.FIXED_TP)

        # --- Trailing SL (ATR-based) ---
        if pos.trailing_atr_mult is not None and atr is not None:
            if pos.direction == Direction.LONG:
                trail_sl = pos.highest_since_entry - (pos.trailing_atr_mult * atr)
                if trail_sl > pos.stop_loss:
                    pos.stop_loss = trail_sl
                if low <= pos.stop_loss:
                    return self.close_position(symbol, pos.stop_loss, bar_idx, bar_date, ExitType.TRAILING_SL)
            else:
                trail_sl = pos.lowest_since_entry + (pos.trailing_atr_mult * atr)
                if trail_sl < pos.stop_loss:
                    pos.stop_loss = trail_sl
                if high >= pos.stop_loss:
                    return self.close_position(symbol, pos.stop_loss, bar_idx, bar_date, ExitType.TRAILING_SL)

        # --- SuperTrend flip exit ---
        if supertrend_dir is not None:
            if pos.direction == Direction.LONG and supertrend_dir == -1:
                return self.close_position(symbol, close, bar_idx, bar_date, ExitType.SUPERTREND_FLIP)
            if pos.direction == Direction.SHORT and supertrend_dir == 1:
                return self.close_position(symbol, close, bar_idx, bar_date, ExitType.SUPERTREND_FLIP)

        # --- Max hold period ---
        if pos.max_hold_bars is not None:
            bars_held = bar_idx - pos.entry_bar
            if bars_held >= pos.max_hold_bars:
                return self.close_position(symbol, close, bar_idx, bar_date, ExitType.MAX_HOLD)

        # --- EOD exit ---
        if is_eod:
            return self.close_position(symbol, close, bar_idx, bar_date, ExitType.EOD)

        return None

    def update_equity(self, date_str: str, prices: Dict[str, float] = None):
        """Update equity curve. Call at end of each bar/day."""
        # Mark-to-market open positions
        mtm = 0
        if prices:
            for sym, pos in self.positions.items():
                if sym in prices:
                    if pos.direction == Direction.LONG:
                        mtm += (prices[sym] - pos.entry_price) * pos.quantity
                    else:
                        mtm += (pos.entry_price - prices[sym]) * pos.quantity

        equity = self.capital + mtm
        self.equity_curve[date_str] = equity

        if equity > self.peak_equity:
            self.peak_equity = equity
        dd = (self.peak_equity - equity) / self.peak_equity
        if dd > self.max_drawdown:
            self.max_drawdown = dd

    def get_results(self) -> BacktestResult:
        """Compute and return final results."""
        result = BacktestResult()

        if not self.trades:
            result.equity_curve = self.equity_curve
            return result

        result.total_trades = len(self.trades)
        result.trades = self.trades
        result.equity_curve = self.equity_curve
        result.exit_reasons = self.exit_reasons

        # Win/loss stats
        wins = [t for t in self.trades if t.pnl > 0]
        losses = [t for t in self.trades if t.pnl <= 0]
        result.winning_trades = len(wins)
        result.losing_trades = len(losses)
        result.win_rate = len(wins) / len(self.trades) * 100 if self.trades else 0

        result.total_pnl = sum(t.pnl for t in self.trades)
        result.total_pnl_pct = result.total_pnl / self.initial_capital * 100

        # Profit factor
        gross_profit = sum(t.pnl for t in wins) if wins else 0
        gross_loss = abs(sum(t.pnl for t in losses)) if losses else 1
        result.profit_factor = gross_profit / gross_loss if gross_loss > 0 else float('inf')

        # Avg win/loss
        result.avg_win = np.mean([t.pnl_pct for t in wins]) if wins else 0
        result.avg_loss = np.mean([t.pnl_pct for t in losses]) if losses else 0
        result.avg_rr = abs(result.avg_win / result.avg_loss) if result.avg_loss != 0 else 0

        result.avg_bars_held = np.mean([t.bars_held for t in self.trades])

        # Long/short breakdown
        long_trades = [t for t in self.trades if t.direction == Direction.LONG]
        short_trades = [t for t in self.trades if t.direction == Direction.SHORT]
        result.long_trades = len(long_trades)
        result.short_trades = len(short_trades)
        result.long_win_rate = len([t for t in long_trades if t.pnl > 0]) / max(len(long_trades), 1) * 100
        result.short_win_rate = len([t for t in short_trades if t.pnl > 0]) / max(len(short_trades), 1) * 100

        # Max drawdown
        result.max_drawdown = self.max_drawdown * 100
        result.max_drawdown_pct = result.max_drawdown

        # CAGR from equity curve
        if self.equity_curve:
            eq_values = list(self.equity_curve.values())
            eq_dates = list(self.equity_curve.keys())
            if len(eq_values) >= 2:
                first_date = pd.Timestamp(eq_dates[0])
                last_date = pd.Timestamp(eq_dates[-1])
                years = max((last_date - first_date).days / 365.25, 0.1)
                final_val = eq_values[-1]
                if final_val > 0 and self.initial_capital > 0:
                    result.cagr = ((final_val / self.initial_capital) ** (1 / years) - 1) * 100
                else:
                    result.cagr = -100.0

        # Sharpe, Sortino from equity curve
        if len(self.equity_curve) >= 20:
            eq_series = pd.Series(self.equity_curve)
            returns = eq_series.pct_change().dropna()
            if len(returns) > 0 and returns.std() > 0:
                result.sharpe_ratio = (returns.mean() / returns.std()) * np.sqrt(252)
                downside = returns[returns < 0]
                if len(downside) > 0 and downside.std() > 0:
                    result.sortino_ratio = (returns.mean() / downside.std()) * np.sqrt(252)

        # Calmar
        if result.max_drawdown > 0:
            result.calmar_ratio = result.cagr / result.max_drawdown

        # Yearly stats
        yearly_trades: Dict[int, List[Trade]] = {}
        for t in self.trades:
            yearly_trades.setdefault(t.year, []).append(t)

        for year, trades in sorted(yearly_trades.items()):
            y_wins = [t for t in trades if t.pnl > 0]
            y_pnl = sum(t.pnl for t in trades)
            y_gross_profit = sum(t.pnl for t in y_wins)
            y_gross_loss = abs(sum(t.pnl for t in trades if t.pnl <= 0))

            result.yearly_stats[year] = {
                'trades': len(trades),
                'wins': len(y_wins),
                'win_rate': len(y_wins) / len(trades) * 100 if trades else 0,
                'pnl': y_pnl,
                'pnl_pct': y_pnl / self.initial_capital * 100,
                'profit_factor': y_gross_profit / y_gross_loss if y_gross_loss > 0 else float('inf'),
                'long_trades': len([t for t in trades if t.direction == Direction.LONG]),
                'short_trades': len([t for t in trades if t.direction == Direction.SHORT]),
            }

        # Monthly returns
        for t in self.trades:
            month_key = t.exit_date[:7]  # 'YYYY-MM'
            result.monthly_returns[month_key] = result.monthly_returns.get(month_key, 0) + t.pnl

        return result

    @staticmethod
    def print_results(result: BacktestResult, label: str = ''):
        """Pretty-print backtest results."""
        print(f'\n{"=" * 60}')
        if label:
            print(f'  {label}')
            print(f'{"=" * 60}')

        print(f'  Trades: {result.total_trades} (L:{result.long_trades} S:{result.short_trades})')
        print(f'  Win Rate: {result.win_rate:.1f}% (L:{result.long_win_rate:.1f}% S:{result.short_win_rate:.1f}%)')
        print(f'  PnL: {result.total_pnl:+,.0f} ({result.total_pnl_pct:+.2f}%)')
        print(f'  Profit Factor: {result.profit_factor:.2f}')
        print(f'  CAGR: {result.cagr:.2f}%')
        print(f'  Max Drawdown: {result.max_drawdown:.2f}%')
        print(f'  Sharpe: {result.sharpe_ratio:.2f} | Sortino: {result.sortino_ratio:.2f} | Calmar: {result.calmar_ratio:.2f}')
        print(f'  Avg Win: {result.avg_win:.2f}% | Avg Loss: {result.avg_loss:.2f}% | Avg RR: {result.avg_rr:.2f}')
        print(f'  Avg Bars Held: {result.avg_bars_held:.1f}')
        print(f'  Exit Reasons: {result.exit_reasons}')

        if result.yearly_stats:
            print(f'\n  Year-by-Year:')
            print(f'  {"Year":>6} {"Trades":>7} {"WR":>6} {"PF":>6} {"PnL":>12} {"PnL%":>8} {"L/S":>7}')
            for year, stats in sorted(result.yearly_stats.items()):
                print(f'  {year:>6} {stats["trades"]:>7} {stats["win_rate"]:>5.1f}% '
                      f'{stats["profit_factor"]:>5.2f} {stats["pnl"]:>+11,.0f} '
                      f'{stats["pnl_pct"]:>+7.2f}% {stats["long_trades"]}/{stats["short_trades"]:>3}')

        print(f'{"=" * 60}\n')


def load_data_from_db(
    symbols: List[str],
    timeframe: str,
    start_date: str = '2018-01-01',
    end_date: str = '2025-12-31',
    db_path: str = None,
) -> Dict[str, pd.DataFrame]:
    """Load OHLCV data from SQLite database."""
    import sqlite3
    import os

    if db_path is None:
        db_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            'backtest_data', 'market_data.db'
        )

    conn = sqlite3.connect(db_path)
    data = {}

    for symbol in symbols:
        query = """
            SELECT date, open, high, low, close, volume
            FROM market_data_unified
            WHERE symbol = ? AND timeframe = ?
            AND date >= ? AND date <= ?
            ORDER BY date
        """
        df = pd.read_sql_query(query, conn, params=(symbol, timeframe, start_date, end_date))

        if len(df) > 0:
            df['date'] = pd.to_datetime(df['date'])
            df = df.set_index('date')
            df = df.sort_index()
            # Extract date string for daily grouping
            df['date_str'] = df.index.strftime('%Y-%m-%d')
            data[symbol] = df

    conn.close()
    return data


def get_all_symbols_for_timeframe(
    timeframe: str,
    min_rows: int = 1000,
    db_path: str = None,
) -> List[str]:
    """Get all symbols with sufficient data for a timeframe."""
    import sqlite3
    import os

    if db_path is None:
        db_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            'backtest_data', 'market_data.db'
        )

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute("""
        SELECT symbol, COUNT(*) as cnt
        FROM market_data_unified
        WHERE timeframe = ?
        GROUP BY symbol
        HAVING cnt >= ?
        ORDER BY symbol
    """, (timeframe, min_rows))
    symbols = [row[0] for row in cur.fetchall()]
    conn.close()
    return symbols
