"""
MQ Agent Report Dataclasses
=============================

Shared data structures used as return types by all MQ agents.
Kept separate to avoid circular imports between agent modules.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional


@dataclass
class MarketRegime:
    """Market regime assessment based on index trend and volatility."""
    index_name: str = 'NIFTY500'
    index_close: float = 0.0
    index_200dma: float = 0.0
    above_200dma: bool = True
    vix: Optional[float] = None
    vix_ok: bool = True  # VIX below panic threshold
    regime: str = 'BULLISH'  # BULLISH, BEARISH, HIGH_VOLATILITY
    allow_entries: bool = True


@dataclass
class MonitoringSignal:
    """Single signal generated by the monitoring agent."""
    signal_type: str  # EXIT, TOPUP, WATCH, WARNING
    symbol: str
    priority: str  # HIGH, MEDIUM, LOW
    details: Dict = field(default_factory=dict)
    message: str = ''


@dataclass
class ScreeningReport:
    """Output of the ScreeningAgent."""
    run_date: datetime = field(default_factory=datetime.now)
    regime: MarketRegime = field(default_factory=MarketRegime)
    total_scanned: int = 0
    momentum_passed: int = 0
    quality_passed: int = 0
    top_ranked: List[Dict] = field(default_factory=list)
    pipeline_candidates: List[Dict] = field(default_factory=list)
    funnel: Dict = field(default_factory=dict)


@dataclass
class MonitoringReport:
    """Output of the MonitoringAgent."""
    run_date: datetime = field(default_factory=datetime.now)
    portfolio_value: float = 0.0
    debt_fund_balance: float = 0.0
    signals: List[MonitoringSignal] = field(default_factory=list)
    position_warnings: List[Dict] = field(default_factory=list)
    sector_warnings: List[Dict] = field(default_factory=list)
    consolidation_count: int = 0
    breakout_count: int = 0


@dataclass
class RebalanceReport:
    """Output of the RebalanceAgent."""
    run_date: datetime = field(default_factory=datetime.now)
    exits: List[Dict] = field(default_factory=list)
    entries: List[Dict] = field(default_factory=list)
    portfolio_before: Dict = field(default_factory=dict)
    portfolio_after: Dict = field(default_factory=dict)
    screening_used: Optional[ScreeningReport] = None


@dataclass
class BacktestReportData:
    """Output of the BacktestAgent."""
    run_date: datetime = field(default_factory=datetime.now)
    config: Dict = field(default_factory=dict)
    metrics: Dict = field(default_factory=dict)
    equity_curve: Dict = field(default_factory=dict)  # date_str -> value
    benchmark_curves: Dict = field(default_factory=dict)  # name -> {date_str: value}
    trade_count: int = 0
    topup_count: int = 0
    sector_allocation: Dict = field(default_factory=dict)
