"""
Notification Service -- Email (Gmail), WhatsApp (Twilio), In-App
================================================================
Provider-agnostic: send alerts via configured channels.
All notifications are also stored in DB for in-app viewing.
"""

import logging
import smtplib
import threading
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, date
from services.orb_db import get_orb_db

logger = logging.getLogger(__name__)


class NotificationService:
    """
    Central notification hub. Call send_alert() or send_eod_report().
    Reads config from ORB_DEFAULTS or passed config dict.
    Dispatches to enabled providers (email, whatsapp, in-app DB).
    """

    def __init__(self, config: dict):
        self.cfg = config
        self.providers = []

        # Always log to DB (in-app notifications tab)
        self.providers.append(InAppProvider())

        # Email provider
        if config.get('email_enabled', True):
            self.providers.append(EmailProvider(config))

        # WhatsApp provider (future)
        if config.get('whatsapp_enabled', False):
            self.providers.append(WhatsAppProvider(config))

    def send_alert(self, alert_type, title, message, data=None, priority='normal'):
        """
        Send a real-time alert.
        alert_type: 'trade_entry', 'trade_exit', 'sl_hit', 'target_hit', 'eod_close',
                    'trade_blocked', 'risk_alert', 'system_alert', 'margin_alert'
        priority: 'low', 'normal', 'high', 'critical'
        data: dict with extra context (symbol, pnl, etc.)
        """
        notification = {
            'type': alert_type,
            'title': title,
            'message': message,
            'data': data or {},
            'priority': priority,
            'timestamp': datetime.now().isoformat(),
        }

        # Send async to avoid blocking the trading engine
        thread = threading.Thread(target=self._dispatch, args=(notification,), daemon=True)
        thread.start()

    def send_eod_report(self, report_data):
        """Send the daily EOD summary report."""
        notification = {
            'type': 'eod_report',
            'title': f"ORB Daily Report -- {date.today().strftime('%d %b %Y')}",
            'message': '',  # HTML generated by provider
            'data': report_data,
            'priority': 'normal',
            'timestamp': datetime.now().isoformat(),
        }
        thread = threading.Thread(target=self._dispatch, args=(notification,), daemon=True)
        thread.start()

    def _dispatch(self, notification):
        for provider in self.providers:
            try:
                provider.send(notification)
            except Exception as e:
                logger.error(f"[Notify] {provider.__class__.__name__} failed: {e}")


class InAppProvider:
    """Store notifications in SQLite for the in-app notifications tab."""

    def send(self, notification):
        try:
            db = get_orb_db()
            db.log_notification(
                type=notification['type'],
                title=notification['title'],
                message=notification['message'],
                data=str(notification.get('data', {})),
                priority=notification['priority'],
            )
        except Exception as e:
            logger.error(f"[InApp] DB log failed: {e}")


class EmailProvider:
    """Send email via Gmail SMTP."""

    def __init__(self, config):
        self.smtp_host = config.get('smtp_host', 'smtp.gmail.com')
        self.smtp_port = config.get('smtp_port', 587)
        self.email_from = config.get('email_from', '')
        self.email_password = config.get('email_app_password', '')  # Gmail App Password
        self.email_to = config.get('email_to', '')  # can be same as from

    def send(self, notification):
        if not self.email_from or not self.email_password or not self.email_to:
            logger.warning("[Email] Not configured, skipping")
            return

        if notification['type'] == 'eod_report':
            subject, html = self._build_eod_email(notification)
        else:
            subject, html = self._build_alert_email(notification)

        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"Quantifyd <{self.email_from}>"
        msg['To'] = self.email_to
        msg.attach(MIMEText(html, 'html'))

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.email_from, self.email_password)
                server.send_message(msg)
            logger.info(f"[Email] Sent: {subject}")
        except Exception as e:
            logger.error(f"[Email] Send failed: {e}")

    def _build_alert_email(self, notification):
        """Build a clean, minimal alert email."""
        data = notification.get('data', {})
        alert_type = notification['type']
        title = notification['title']
        message = notification['message']
        priority = notification['priority']
        timestamp = notification.get('timestamp', '')

        # Icon and color based on type
        type_styles = {
            'trade_entry': ('\U0001f7e2', '#3fb950', 'Trade Entry'),
            'target_hit': ('\U0001f3af', '#3fb950', 'Target Hit'),
            'sl_hit': ('\U0001f534', '#f85149', 'Stop Loss Hit'),
            'eod_close': ('\u23f0', '#58a6ff', 'EOD Squareoff'),
            'trade_blocked': ('\u26a0\ufe0f', '#f59e0b', 'Trade Blocked'),
            'risk_alert': ('\U0001f6a8', '#f85149', 'Risk Alert'),
            'system_alert': ('\u2699\ufe0f', '#f85149', 'System Alert'),
            'margin_alert': ('\U0001f4b0', '#f59e0b', 'Margin Alert'),
            'login_success': ('\u2705', '#3fb950', 'Login'),
            'login_failed': ('\U0001f6a8', '#f85149', 'Login Failed'),
        }
        icon, color, label = type_styles.get(alert_type, ('\U0001f4cc', '#8b949e', 'Alert'))

        # Build details table from data dict
        details_html = ''
        if data:
            rows = ''
            display_keys = [
                'symbol', 'direction', 'entry_price', 'sl_price', 'target_price',
                'exit_price', 'exit_reason', 'pnl_pts', 'pnl_inr', 'qty',
                'available_margin', 'required_margin', 'holding_time',
            ]
            for key in display_keys:
                if key in data:
                    val = data[key]
                    if isinstance(val, float):
                        if 'inr' in key or 'margin' in key:
                            val = f"Rs {val:,.2f}"
                        elif 'price' in key or 'pnl' in key:
                            val = f"{val:.2f}"
                    label_text = key.replace('_', ' ').title()
                    val_color = '#3fb950' if 'pnl' in key and isinstance(data[key], (int, float)) and data[key] > 0 else (
                        '#f85149' if 'pnl' in key and isinstance(data[key], (int, float)) and data[key] < 0 else '#c9d1d9'
                    )
                    rows += (
                        f'<tr>'
                        f'<td style="padding:4px 12px 4px 0;color:#8b949e;font-size:13px;">{label_text}</td>'
                        f'<td style="padding:4px 0;color:{val_color};font-weight:600;font-size:13px;">{val}</td>'
                        f'</tr>'
                    )
            if rows:
                details_html = f'<table style="margin-top:12px;">{rows}</table>'

        subject = f"[Quantifyd] {icon} {title}"

        html = f"""
        <div style="font-family:'Inter',system-ui,-apple-system,sans-serif;max-width:480px;margin:0 auto;background:#0d1117;border-radius:12px;overflow:hidden;border:1px solid #30363d;">
            <div style="background:{color}15;border-bottom:2px solid {color};padding:16px 20px;">
                <span style="font-size:20px;margin-right:8px;">{icon}</span>
                <span style="color:{color};font-weight:700;font-size:15px;">{label}</span>
                <span style="float:right;color:#8b949e;font-size:12px;">{timestamp[11:16] if len(timestamp) > 16 else ''}</span>
            </div>
            <div style="padding:16px 20px;">
                <div style="color:#c9d1d9;font-size:14px;font-weight:600;margin-bottom:8px;">{title}</div>
                <div style="color:#8b949e;font-size:13px;line-height:1.5;">{message}</div>
                {details_html}
            </div>
            <div style="padding:8px 20px;border-top:1px solid #30363d;text-align:center;">
                <a href="http://94.136.185.54:5000/orb" style="color:{color};font-size:11px;text-decoration:none;">Open Dashboard &rarr;</a>
            </div>
        </div>
        """
        return subject, html

    def _build_eod_email(self, notification):
        """Build a comprehensive, visual EOD summary report."""
        data = notification.get('data', {})
        today = date.today().strftime('%d %b %Y')
        weekday = date.today().strftime('%A')

        trades = data.get('trades', [])
        total_trades = len(trades)
        winners = [t for t in trades if (t.get('pnl_inr') or 0) > 0]
        losers = [t for t in trades if (t.get('pnl_inr') or 0) <= 0]
        day_pnl = sum(t.get('pnl_inr', 0) or 0 for t in trades)
        cum_pnl = data.get('cumulative_pnl', 0)
        win_rate = len(winners) / total_trades * 100 if total_trades > 0 else 0

        blocked = data.get('blocked_signals', [])
        errors = data.get('errors', [])
        margin_info = data.get('margin', {})

        # PnL color
        pnl_color = '#3fb950' if day_pnl >= 0 else '#f85149'
        pnl_sign = '+' if day_pnl >= 0 else ''

        # Trade rows
        trade_rows = ''
        for t in trades:
            pnl = t.get('pnl_inr', 0) or 0
            tc = '#3fb950' if pnl > 0 else '#f85149'
            if t.get('exit_reason') == 'target':
                ticon = '\U0001f3af'
            elif t.get('exit_reason') == 'sl':
                ticon = '\U0001f534'
            else:
                ticon = '\u23f0'
            trade_rows += f"""
            <tr>
                <td style="padding:6px 8px;color:#c9d1d9;font-size:13px;">{ticon} {t.get('instrument', '')}</td>
                <td style="padding:6px 8px;color:#8b949e;font-size:13px;">{t.get('direction', '').upper()}</td>
                <td style="padding:6px 8px;color:#8b949e;font-size:13px;">{t.get('entry_price', '')}</td>
                <td style="padding:6px 8px;color:#8b949e;font-size:13px;">{t.get('exit_price', '')}</td>
                <td style="padding:6px 8px;color:{tc};font-weight:700;font-size:13px;">{pnl_sign if pnl >= 0 else ''}Rs {pnl:,.0f}</td>
                <td style="padding:6px 8px;color:#8b949e;font-size:12px;">{(t.get('exit_reason') or '').upper()}</td>
            </tr>"""

        if not trade_rows:
            trade_rows = '<tr><td colspan="6" style="padding:12px;color:#8b949e;text-align:center;font-size:13px;">No trades today</td></tr>'

        # Blocked signals
        blocked_html = ''
        if blocked:
            blocked_rows = ''
            for b in blocked[:5]:
                blocked_rows += f'<div style="padding:4px 0;color:#8b949e;font-size:12px;">\u23ed\ufe0f {b.get("instrument", "")} -- {b.get("reason", "")}</div>'
            blocked_html = f"""
            <div style="margin-top:16px;">
                <div style="color:#f59e0b;font-weight:600;font-size:13px;margin-bottom:8px;">Blocked Signals ({len(blocked)})</div>
                {blocked_rows}
            </div>"""

        # Errors/Issues
        errors_html = ''
        if errors:
            error_rows = ''.join(
                f'<div style="padding:4px 0;color:#f85149;font-size:12px;">\u26a0\ufe0f {e}</div>'
                for e in errors[:5]
            )
            errors_html = f"""
            <div style="margin-top:16px;padding:12px;background:#f8514915;border:1px solid #f8514930;border-radius:8px;">
                <div style="color:#f85149;font-weight:600;font-size:13px;margin-bottom:8px;">Issues ({len(errors)})</div>
                {error_rows}
            </div>"""

        subject = f"[Quantifyd] \U0001f4ca ORB {weekday}: {pnl_sign}Rs {abs(day_pnl):,.0f} | {total_trades} trades ({len(winners)}W {len(losers)}L)"

        html = f"""
        <div style="font-family:'Inter',system-ui,-apple-system,sans-serif;max-width:560px;margin:0 auto;background:#0d1117;border-radius:12px;overflow:hidden;border:1px solid #30363d;">

            <!-- Header -->
            <div style="background:linear-gradient(135deg,#06b6d415,#0d1117);padding:20px 24px;border-bottom:2px solid #06b6d4;">
                <div style="color:#06b6d4;font-weight:800;font-size:16px;">\U0001f4ca ORB Daily Report</div>
                <div style="color:#8b949e;font-size:12px;margin-top:4px;">{weekday}, {today} | 15 Stocks | Cash MIS</div>
            </div>

            <!-- Summary Stats -->
            <div style="padding:20px 24px;">
                <table style="width:100%;text-align:center;">
                    <tr>
                        <td style="padding:8px;">
                            <div style="color:{pnl_color};font-size:24px;font-weight:800;">{pnl_sign}Rs {abs(day_pnl):,.0f}</div>
                            <div style="color:#8b949e;font-size:11px;text-transform:uppercase;letter-spacing:1px;">Day P&L</div>
                        </td>
                        <td style="padding:8px;">
                            <div style="color:#c9d1d9;font-size:24px;font-weight:800;">{total_trades}</div>
                            <div style="color:#8b949e;font-size:11px;text-transform:uppercase;letter-spacing:1px;">Trades</div>
                        </td>
                        <td style="padding:8px;">
                            <div style="color:#3fb950;font-size:24px;font-weight:800;">{win_rate:.0f}%</div>
                            <div style="color:#8b949e;font-size:11px;text-transform:uppercase;letter-spacing:1px;">Win Rate</div>
                        </td>
                    </tr>
                </table>

                <!-- Cumulative -->
                <div style="text-align:center;margin-top:8px;padding:8px;background:#30363d30;border-radius:8px;">
                    <span style="color:#8b949e;font-size:12px;">Cumulative P&L: </span>
                    <span style="color:{'#3fb950' if cum_pnl >= 0 else '#f85149'};font-weight:700;font-size:14px;">{'+'if cum_pnl>=0 else ''}Rs {cum_pnl:,.0f}</span>
                </div>
            </div>

            <!-- Trades Table -->
            <div style="padding:0 24px 16px;">
                <div style="color:#c9d1d9;font-weight:600;font-size:13px;margin-bottom:8px;">Trades</div>
                <table style="width:100%;border-collapse:collapse;">
                    <tr style="border-bottom:1px solid #30363d;">
                        <th style="padding:6px 8px;color:#8b949e;font-size:11px;text-align:left;text-transform:uppercase;">Stock</th>
                        <th style="padding:6px 8px;color:#8b949e;font-size:11px;text-align:left;text-transform:uppercase;">Dir</th>
                        <th style="padding:6px 8px;color:#8b949e;font-size:11px;text-align:left;text-transform:uppercase;">Entry</th>
                        <th style="padding:6px 8px;color:#8b949e;font-size:11px;text-align:left;text-transform:uppercase;">Exit</th>
                        <th style="padding:6px 8px;color:#8b949e;font-size:11px;text-align:left;text-transform:uppercase;">P&L</th>
                        <th style="padding:6px 8px;color:#8b949e;font-size:11px;text-align:left;text-transform:uppercase;">Reason</th>
                    </tr>
                    {trade_rows}
                </table>
            </div>

            {blocked_html}
            {errors_html}

            <!-- Margin Info -->
            <div style="padding:12px 24px;border-top:1px solid #30363d;">
                <span style="color:#8b949e;font-size:12px;">Available Margin: </span>
                <span style="color:#c9d1d9;font-size:12px;font-weight:600;">Rs {margin_info.get('available', 0):,.0f}</span>
                <span style="color:#8b949e;font-size:12px;margin-left:12px;">Capital: </span>
                <span style="color:#c9d1d9;font-size:12px;font-weight:600;">Rs {data.get('capital', 100000):,.0f}</span>
            </div>

            <!-- Footer -->
            <div style="padding:12px 24px;border-top:1px solid #30363d;text-align:center;">
                <a href="http://94.136.185.54:5000/orb" style="color:#06b6d4;font-size:12px;text-decoration:none;">Open Dashboard &rarr;</a>
                <span style="color:#30363d;margin:0 8px;">|</span>
                <span style="color:#8b949e;font-size:11px;">Quantifyd ORB v1.0</span>
            </div>
        </div>
        """
        return subject, html


class WhatsAppProvider:
    """Send WhatsApp messages via Twilio. Stub -- to be implemented."""

    def __init__(self, config):
        self.account_sid = config.get('twilio_account_sid', '')
        self.auth_token = config.get('twilio_auth_token', '')
        self.from_number = config.get('twilio_whatsapp_from', '')
        self.to_number = config.get('twilio_whatsapp_to', '')

    def send(self, notification):
        if not all([self.account_sid, self.auth_token, self.from_number, self.to_number]):
            return

        # Build plain text message for WhatsApp
        if notification['type'] == 'eod_report':
            text = self._build_eod_text(notification)
        else:
            text = f"{notification['title']}\n{notification['message']}"

        try:
            from twilio.rest import Client
            client = Client(self.account_sid, self.auth_token)
            client.messages.create(
                body=text,
                from_=self.from_number,
                to=self.to_number,
            )
            logger.info(f"[WhatsApp] Sent: {notification['title'][:50]}")
        except Exception as e:
            logger.error(f"[WhatsApp] Send failed: {e}")

    def _build_eod_text(self, notification):
        data = notification.get('data', {})
        trades = data.get('trades', [])
        day_pnl = sum(t.get('pnl_inr', 0) or 0 for t in trades)
        winners = len([t for t in trades if (t.get('pnl_inr') or 0) > 0])
        losers = len(trades) - winners

        lines = [
            f"\U0001f4ca *ORB Daily Report* -- {date.today().strftime('%d %b %Y')}",
            f"",
            f"Trades: {len(trades)} ({winners}W {losers}L)",
            f"Day P&L: {'+'if day_pnl>=0 else ''}Rs {day_pnl:,.0f}",
            f"Cumulative: {'+'if data.get('cumulative_pnl',0)>=0 else ''}Rs {data.get('cumulative_pnl',0):,.0f}",
            f"",
        ]
        for t in trades:
            pnl = t.get('pnl_inr', 0) or 0
            if t.get('exit_reason') == 'target':
                ticon = '\U0001f3af'
            elif t.get('exit_reason') == 'sl':
                ticon = '\U0001f534'
            else:
                ticon = '\u23f0'
            lines.append(f"{ticon} {t.get('instrument', '')} {t.get('direction', '').upper()} {'+'if pnl>=0 else ''}Rs {pnl:,.0f}")

        return '\n'.join(lines)


# --- Singleton ---

_instance = None
_lock = threading.Lock()


def get_notification_service(config=None):
    global _instance
    if _instance is None:
        with _lock:
            if _instance is None:
                if config is None:
                    from config import ORB_DEFAULTS
                    config = ORB_DEFAULTS
                _instance = NotificationService(config)
    return _instance
