# -*- coding: utf-8 -*-
"""research/165 - IS THE RATE GAP THE PERIOD, OR IS THE LIVE CODE WRONG?

The live-code walk (rot1_gate.py R2) fired ~12 swaps a year over 2025-01-31 -> 2026-09-11 and
LOST on every arm. research/170 reports 4.5 swaps a year over 21.7 years and wins 30/30. The
pick logic is identical (8,488/8,488), so the difference has to be either the PERIOD or the
"the book cannot take it" condition around the pick - cash refusals under real integer sizing,
the NAV basis, the traded-value tie-break.

This settles it by running research/170's OWN engine, with its rule untouched, over exactly
that window: once from an empty book at the live book's capital, once opening with the live
book's eleven positions and its cash. 30 seeds each, plus the live `select='tv'` tie-break.

  If the study engine also fires ~12/yr and loses here -> the gap is the period, and the live
  code is faithful.
  If it fires ~4-5/yr here -> the live code differs somewhere and must be fixed before a flip.

The engine is `sim170_probe.py`, regenerated by `patch_probe170.py`, whose only additions are
a decision probe (off here) and two lines that set the opening cash and opening positions from
cfg. No rule, no filter, no ordering is touched; `--verify` proves the no-op.

    python3 research/165_oa_baseage_live_conversion/scripts/rot1_window.py [--seeds=30]
"""
import json
import pickle
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
RES = HERE.parent / 'results'
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / 'research/170_qs_leeway_and_baseage_best_entrant/scripts'))
sys.path.insert(0, str(HERE))
import sim170_probe as S                                                   # noqa: E402

PANEL_PKL = ROOT / 'research/164_baseage_slots_sizing/results/panel164.pkl'
ST_PKL = ROOT / 'research/166_baseage_rotation_and_drift/results/st166.pkl'
EV166 = ROOT / 'research/166_baseage_rotation_and_drift/results/events166.csv'

LO, HI = '2025-01-31', '2026-09-11'          # the live-code walk's own 400-session window
CAPITAL = 617637.68
LIVE_CASH = 188697.86
LIVE_POSITIONS = [
    dict(symbol='INDSWFTLAB', qty=99, buy=362.33), dict(symbol='SETL', qty=99, buy=402.69),
    dict(symbol='WELCORP', qty=14, buy=2596.36), dict(symbol='SHILPAMED', qty=40, buy=962.36),
    dict(symbol='SBCL', qty=34, buy=1115.48), dict(symbol='IRISDOREME', qty=634, buy=62.39),
    dict(symbol='INOXINDIA', qty=17, buy=2236.50), dict(symbol='MANINDS', qty=47, buy=800.19),
    dict(symbol='SSWL', qty=106, buy=358.30), dict(symbol='ENTERO', qty=21, buy=1843.72),
    dict(symbol='NITINSPIN', qty=61, buy=636.65),
]

BASE = dict(exit='ST_14_4', hard_stop=False, hard_stop_pct=0.92, rot_sell_only=False,
            time_stop=0, cost_bps=25.0, gate_ok=None, idle_yield=0.052, slots=16,
            slot_pct=0.0625, select='random', rot_score=None, rot_margin=0.0,
            rot_max_per_day=1, rot_entrant='tv', trim_mult=0.0, trim_when='month',
            min_fill_frac=0.0)
ROT = dict(rot_score='unreal', rot_margin=10.0, rot_entrant='rs')


class Slice:
    """A Panel restricted to [a, b). Same attribute surface, arrays sliced, nothing recomputed.

    The SuperTrend signals, the rs252 aux and the all-time-high state all carry their full
    history into the window, because they are sliced AFTER being computed on the whole panel.
    A window that recomputed them would start every indicator from scratch on day one and
    would not be the same book.
    """

    def __init__(self, panel, a, b):
        self.cal = list(panel.cal[a:b])
        self.n = b - a
        self.pos = {d: i for i, d in enumerate(self.cal)}
        self.open = {s: v[a:b] for s, v in panel.open.items()}
        self.close = {s: v[a:b] for s, v in panel.close.items()}
        self.sig = {s: {k: v[a:b] for k, v in d.items()} for s, d in panel.sig.items()}

    def has(self, s):
        return s in self.close


def main():
    seeds_n = 30
    for a in sys.argv[1:]:
        if a.startswith('--seeds='):
            seeds_n = int(a.split('=', 1)[1])
    t0 = time.time()
    panel = pickle.load(open(PANEL_PKL, 'rb'))
    st = pickle.load(open(ST_PKL, 'rb'))
    aux_full = S.build_aux(panel, st)
    a = panel.pos[LO]
    b = panel.pos[HI] + 1
    sl = Slice(panel, a, b)
    aux = dict(st={k: v[a:b] for k, v in aux_full['st'].items()},
               rs={k: v[a:b] for k, v in aux_full['rs'].items()},
               athd={k: v[a:b] for k, v in aux_full['athd'].items()})
    ev = pd.read_csv(EV166)
    events = []
    for e in ev.to_dict('records'):
        i = int(e['entry_i'])
        if a <= i < b:
            e['entry_i'] = i - a
            events.append(e)
    print('window %s .. %s -> %d sessions (%.2f yrs), %d events, loaded in %.0fs'
          % (sl.cal[0], sl.cal[-1], sl.n, sl.n / 252.0, len(events), time.time() - t0),
          flush=True)

    seeded = [p for p in LIVE_POSITIONS if p['symbol'] in sl.close]
    missing = [p['symbol'] for p in LIVE_POSITIONS if p['symbol'] not in sl.close]
    if missing:
        print('NOTE: %d live position(s) are not in research/164\'s panel and cannot be '
              'seeded: %s' % (len(missing), ', '.join(missing)))
    yrs = sl.n / 252.0
    seeds = list(range(1001, 1001 + seeds_n))

    out = {}
    for book, pos, cash0 in (('empty', [], CAPITAL), ('live-11', seeded, LIVE_CASH)):
        for sel in ('random', 'tv'):
            use = seeds if sel == 'random' else [1001]
            rows = {}
            for arm, extra in (('norot', {}), ('rot1', ROT)):
                r = []
                for sd in use:
                    cfg = dict(BASE, select=sel, start_capital=cash0, seed_positions=pos,
                               **extra)
                    nav, tr, inv, bk = S.simulate(events, sl, aux, cfg, sd)
                    r.append((sd, float(np.nanmax(np.where(np.isfinite(nav), nav, -1)[-1:])),
                              bk['swaps'], bk['cash_refused'], bk['turned_away'],
                              bk['entries_taken']))
                rows[arm] = r
            d = [rows['rot1'][k][1] - rows['norot'][k][1] for k in range(len(use))]
            wins = sum(1 for x in d if x > 0)
            sw = [x[2] for x in rows['rot1']]
            key = '%s/%s' % (book, sel)
            out[key] = dict(
                n=len(use), swaps_med=float(np.median(sw)),
                swaps_per_yr=round(float(np.median(sw)) / yrs, 2),
                nav_norot=round(float(np.median([x[1] for x in rows['norot']]))),
                nav_rot1=round(float(np.median([x[1] for x in rows['rot1']]))),
                dnav_med=round(float(np.median(d))), wins=wins,
                cash_refused_norot=float(np.median([x[3] for x in rows['norot']])),
                cash_refused_rot1=float(np.median([x[3] for x in rows['rot1']])),
                turned_away=float(np.median([x[4] for x in rows['norot']])),
                entries_norot=float(np.median([x[5] for x in rows['norot']])),
                entries_rot1=float(np.median([x[5] for x in rows['rot1']])))
            o = out[key]
            print('  %-14s %-7s n=%2d | swaps %5.1f (%5.2f/yr) | NAV norot %9s  rot1 %9s  '
                  'dNAV %+9s  rot1 wins %2d/%2d | cash-refused %4.0f->%4.0f | entries '
                  '%4.0f->%4.0f'
                  % (book, sel, o['n'], o['swaps_med'], o['swaps_per_yr'],
                     format(o['nav_norot'], ','), format(o['nav_rot1'], ','),
                     format(o['dnav_med'], ','), o['wins'], o['n'],
                     o['cash_refused_norot'], o['cash_refused_rot1'],
                     o['entries_norot'], o['entries_rot1']), flush=True)

    out['_window'] = dict(lo=sl.cal[0], hi=sl.cal[-1], sessions=sl.n, years=round(yrs, 2),
                          events=len(events), seeded=[p['symbol'] for p in seeded],
                          not_seedable=missing)
    json.dump(out, open(RES / 'rot1_window.json', 'w'), indent=1)
    print('\nresearch/170 headline for comparison: 4.5 swaps/yr over 21.7 years, '
          '+0.105 paired Calmar on 30/30 fresh seeds.')


if __name__ == '__main__':
    main()
