import { useEffect, useMemo, useRef, useState } from 'react';
import styles from './MomentumScanner.module.css';

// Momentum-30 scanner (research/62) — reads the precomputed static scan + OHLC files
// (static/momentum_scan.json, static/scan_ohlc.json), regenerated by a daily cron / on demand.
// Scan → select rows → add to a localStorage watchlist that shows the same candles.

interface ScanRow {
  rank: number; symbol: string; score: number; ret_6m: number; ret_12m: number;
  price: number; tier: string; in_top: boolean;
}
interface ScanData {
  asof?: string; generated?: string; bench?: string; top_n?: number; count?: number;
  rows?: ScanRow[]; error?: string;
}
interface Bar { t: string; o: number; h: number; l: number; c: number; v: number; }

const WATCH_KEY = 'holdingsWatchlist';
function loadWatch(): string[] { try { return JSON.parse(localStorage.getItem(WATCH_KEY) || '[]'); } catch { return []; } }
function saveWatch(w: string[]) { try { localStorage.setItem(WATCH_KEY, JSON.stringify(w)); } catch { /* ignore */ } }

function readVar(n: string) { return getComputedStyle(document.documentElement).getPropertyValue(n).trim() || '#888'; }

// compact candlestick spark for a watchlist row (last ~90 daily bars)
function drawSpark(cv: HTMLCanvasElement, bars: Bar[]) {
  const W = cv.clientWidth || 220, H = cv.clientHeight || 56;
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  cv.width = W * dpr; cv.height = H * dpr;
  const x = cv.getContext('2d'); if (!x) return;
  x.setTransform(dpr, 0, 0, dpr, 0, 0);
  const bs = bars.slice(-90);
  if (bs.length < 2) return;
  const pad = 3, n = bs.length;
  const lo = Math.min(...bs.map((b) => b.l)), hi = Math.max(...bs.map((b) => b.h));
  const rng = hi - lo || 1;
  const slot = (W - 2 * pad) / n;
  const bw = Math.max(1, Math.min(slot * 0.7, 5));
  const px = (i: number) => pad + slot * i + slot / 2;
  const py = (v: number) => H - pad - ((v - lo) / rng) * (H - 2 * pad);
  const pos = readVar('--accent-pos'), neg = readVar('--accent-neg');
  x.clearRect(0, 0, W, H);
  bs.forEach((b, i) => {
    const up = b.c >= b.o, col = up ? pos : neg;
    x.strokeStyle = col; x.fillStyle = col; x.lineWidth = 1;
    const cx = px(i);
    x.beginPath(); x.moveTo(cx, py(b.h)); x.lineTo(cx, py(b.l)); x.stroke();
    const yo = py(b.o), yc = py(b.c);
    x.fillRect(cx - bw / 2, Math.min(yo, yc), bw, Math.max(1, Math.abs(yc - yo)));
  });
}

function Spark({ bars }: { bars?: Bar[] }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const cv = ref.current; if (!cv || !bars) return;
    const draw = () => drawSpark(cv, bars);
    const raf = requestAnimationFrame(draw);
    const ro = new ResizeObserver(draw); ro.observe(cv);
    return () => { cancelAnimationFrame(raf); ro.disconnect(); };
  }, [bars]);
  if (!bars || bars.length < 2) return <div className={styles.sparkEmpty}>no chart data</div>;
  return <canvas ref={ref} className={styles.sparkCv} />;
}

const pct = (n: number) => `${n >= 0 ? '+' : ''}${n.toFixed(1)}%`;

export default function MomentumScanner({ heldSyms }: { heldSyms: Set<string> }) {
  const [data, setData] = useState<ScanData | null>(null);
  const [ohlc, setOhlc] = useState<Record<string, Bar[]>>({});
  const [loading, setLoading] = useState(false);
  const [topOnly, setTopOnly] = useState(true);
  const [hideHeld, setHideHeld] = useState(false);
  const [sel, setSel] = useState<Set<string>>(new Set());
  const [watch, setWatch] = useState<string[]>(loadWatch);

  const load = () => {
    setLoading(true);
    Promise.all([
      fetch(`/static/momentum_scan.json?t=${Date.now()}`, { cache: 'no-store' }).then((r) => (r.ok ? r.json() : null)).catch(() => null),
      fetch(`/static/scan_ohlc.json?t=${Date.now()}`, { cache: 'no-store' }).then((r) => (r.ok ? r.json() : null)).catch(() => null),
    ]).then(([s, o]) => {
      if (s) setData(s);
      if (o && o.symbols) setOhlc(o.symbols as Record<string, Bar[]>);
    }).finally(() => setLoading(false));
  };
  useEffect(() => { load(); }, []);

  const rows = useMemo(() => {
    let r = data?.rows ?? [];
    if (topOnly) r = r.filter((x) => x.in_top);
    if (hideHeld) r = r.filter((x) => !heldSyms.has(x.symbol));
    return r;
  }, [data, topOnly, hideHeld, heldSyms]);

  const maxScore = useMemo(() => Math.max(1, ...(data?.rows ?? []).map((r) => r.score)), [data]);
  const rowBySym = useMemo(() => {
    const m: Record<string, ScanRow> = {};
    (data?.rows ?? []).forEach((r) => { m[r.symbol] = r; });
    return m;
  }, [data]);

  const toggleSel = (s: string) => setSel((prev) => {
    const n = new Set(prev); if (n.has(s)) n.delete(s); else n.add(s); return n;
  });
  const addToWatch = () => {
    const n = Array.from(new Set([...watch, ...Array.from(sel)]));
    setWatch(n); saveWatch(n); setSel(new Set());
  };
  const removeWatch = (s: string) => { const n = watch.filter((x) => x !== s); setWatch(n); saveWatch(n); };

  return (
    <section className={styles.root}>
      <div className={styles.head}>
        <div>
          <div className={styles.title}>Momentum Scanner</div>
          <div className={styles.sub}>
            research/62 · Nifty-200 ranked by 6m + 12m relative strength vs {data?.bench ?? 'NIFTYBEES'}
            {data?.asof ? ` · as of ${data.asof}` : ''}{data?.generated ? ` · gen ${data.generated}` : ''}
          </div>
        </div>
        <div className={styles.headCtl}>
          <label className={styles.chk}><input type="checkbox" checked={topOnly} onChange={(e) => setTopOnly(e.target.checked)} /> Top {data?.top_n ?? 30} only</label>
          <label className={styles.chk}><input type="checkbox" checked={hideHeld} onChange={(e) => setHideHeld(e.target.checked)} /> Hide held</label>
          <button className={styles.refresh} onClick={load} disabled={loading}>{loading ? 'Loading…' : '↻ Refresh'}</button>
        </div>
      </div>

      {data?.error ? (
        <div className={styles.empty}>Scan unavailable ({data.error}). The daily generator may not have run yet.</div>
      ) : !data ? (
        <div className={styles.empty}>Loading scan…</div>
      ) : (
        <>
          {sel.size > 0 ? (
            <div className={styles.selBar}>
              <span>{sel.size} selected</span>
              <button className={styles.addBtn} onClick={addToWatch}>Add to watchlist →</button>
              <button className={styles.clearSel} onClick={() => setSel(new Set())}>clear</button>
            </div>
          ) : null}

          <div className={styles.tableWrap}>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th></th><th>#</th><th>Symbol</th><th>Tier</th><th className={styles.num}>Price</th>
                  <th className={styles.num}>6m</th><th className={styles.num}>12m</th><th>RS score</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => {
                  const held = heldSyms.has(r.symbol);
                  const onW = watch.includes(r.symbol);
                  return (
                    <tr key={r.symbol} className={sel.has(r.symbol) ? styles.rowSel : ''}>
                      <td><input type="checkbox" checked={sel.has(r.symbol)} onChange={() => toggleSel(r.symbol)} /></td>
                      <td className={styles.rank}>{r.rank}</td>
                      <td className={styles.sym}>
                        {r.symbol}
                        {held ? <span className={styles.badgeHeld}>held</span> : null}
                        {onW ? <span className={styles.badgeWatch}>watch</span> : null}
                      </td>
                      <td className={styles.tier}>{r.tier}</td>
                      <td className={styles.num}>{r.price.toFixed(1)}</td>
                      <td className={`${styles.num} ${r.ret_6m >= 0 ? styles.up : styles.dn}`}>{pct(r.ret_6m)}</td>
                      <td className={`${styles.num} ${r.ret_12m >= 0 ? styles.up : styles.dn}`}>{pct(r.ret_12m)}</td>
                      <td>
                        <div className={styles.scoreBar}>
                          <div className={styles.scoreFill} style={{ width: `${Math.min(100, (r.score / maxScore) * 100)}%` }} />
                          <span className={styles.scoreVal}>{r.score.toFixed(2)}</span>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <div className={styles.watchHead}>Watchlist <span className={styles.watchCnt}>{watch.length}</span></div>
          {watch.length === 0 ? (
            <div className={styles.empty}>No watchlist yet — tick rows above and “Add to watchlist”.</div>
          ) : (
            <div className={styles.watchGrid}>
              {watch.map((s) => {
                const r = rowBySym[s];
                return (
                  <div key={s} className={styles.watchCard}>
                    <div className={styles.watchTop}>
                      <span className={styles.watchSym}>{s}{heldSyms.has(s) ? <span className={styles.badgeHeld}>held</span> : null}</span>
                      <button className={styles.rmBtn} onClick={() => removeWatch(s)} title="Remove">×</button>
                    </div>
                    <Spark bars={ohlc[s]} />
                    {r ? (
                      <div className={styles.watchMeta}>
                        <span>#{r.rank}</span>
                        <span className={r.ret_6m >= 0 ? styles.up : styles.dn}>6m {pct(r.ret_6m)}</span>
                        <span className={r.ret_12m >= 0 ? styles.up : styles.dn}>12m {pct(r.ret_12m)}</span>
                        <span>₹{r.price.toFixed(1)}</span>
                      </div>
                    ) : (
                      <div className={styles.watchMeta}><span className={styles.dn}>not in latest scan</span></div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </>
      )}
    </section>
  );
}
